### ISSUE TITLE
React Native Example start error.

### ISSUE THREAD

**Issue by gcoakleyjr** [connectrpc/examples-es#1573]
Hello,

When trying to open the react native example in either web, android, or ios, I get hit with an error.

> ERROR in ./node_modules/expo/build/launch/withDevTools.web.js
> Module build failed (from ./node_modules/babel-loader/lib/index.js):
> SyntaxError: /Users/giovannicoakley/Documents/demo/connectrpc examples-es main react-native/node_modules/expo/build/launch/withDevTools.web.js: Duplicate __self prop found. You are most likely using the deprecated transform-react-jsx-self Babel plugin. Both __source and __self are automatically set when using the automatic runtime. Please remove transform-react-jsx-source and transform-react-jsx-self from your Babel config.
>   4 |     function WithDevTools(props) {
>   5 |         return (<>
>  ->6 |         <AppRootComponent {...props}/>
>     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   7 |         <DevLoadingView />
>   8 |       </>);
>   9 |     }
>     at File.buildError [as buildCodeFrameError] (/Users/giovannicoakley/Documents/demo/connectrpc examples-es main react-native/node_modules/@babel/core/src/transformation/file/file.ts:249:12)
> 

This is after downloading the repo, running npm install and then npm start.

**Comment by smaye81** [comment]
@gcoakleyjr This should hopefully be fixed now. Please pull latest and give the `react-native` commands a try.
