### ISSUE TITLE
Documentation Request: Explain when to use HTTP2 vs HTTP1

### ISSUE THREAD

**Issue by sbussard-inversemetric** [connectrpc/examples-es#1883]
After miles of research I found out this information which would be helpful for others to know.
I'm open to new information, but this is what I found.

- [Browsers can't talk directly to http2 servers](https://caniuse.com/http2).
    - It will give an `ERR_INVALID_HTTP_RESPONSE`
- An nginx reverse proxy with a `grpc_pass` statement can't talk directly to an http1 server. 
    - nginx will give an error like `upstream sent too large http2 frame`
    - the browser will show something like `...blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by srikrsna-buf** [comment]
Hey! If you're using clients on the browser, you should use the dedicated `@connectrpc/connect-web` package. Under the hood It just uses `fetch`. 


> [Browsers can't talk directly to http2 servers](https://caniuse.com/http2).

This is not entirely true, browsers can and will even prefer H/2. But H/2 will only work on a secure connection, because of the way protocol negotiation works. H/2 over an insecure connection doesn't work on browsers. Also browsers don't expose `trailers` or full-duplex streaming capabilities to the user code.

> * An nginx reverse proxy with a `grpc_pass` statement can't talk directly to an http1 server

gRPC works only H/2 and relies on `trailers`, so it won't work on H/1. If you want to use H/1 you should use Connect or gRPC-Web protocols. They work on H/1 except for full-duplex streaming.

**Comment by sbussard-inversemetric** [comment]
Ok that makes sense. I wonder if it's worth explaining up front in the docs for newbies.

It feels pretty tricky to set up if you don't know
- connect supports HTTP/1 and HTTP/2
- browsers need ssl for H/2
- nginx grpc_pass needs H/2
- the errors given by nginx and browsers are confusing and incorrect

But at least this github issue exists so it can be another data point for those who might be struggling.
Feel free to close if there's no further action to take

**Comment by sbussard-inversemetric** [comment]
Ran into a similar issue with kubernetes ingress-nginx. 
Solution is here: https://kubernetes.github.io/ingress-nginx/examples/grpc/

add to ingress metadata.annotations
`nginx.ingress.kubernetes.io/backend-protocol: "GRPC"`

add to service spec.ports
`protocol: TCP`

**Comment by timostamm** [comment]
We have a table showing support for web browsers and protocols here: https://connectrpc.com/docs/node/server-plugins#http2-tls-and-grpc We may want to surface this information a bit more prominently, not just under the Node.js section.

We have a FAQ entry for nginx here: https://connectrpc.com/docs/faq/#how-do-i-proxy-the-connect-protocol-through-nginx It seems like this one might be outdated 🤔

**Comment by sbussard** [comment]
Thanks for your response. It looks like there's some really good info already available which I didn't see where I was reading in the docs. 

I think part of the challenge is knowing if the issues someone encounters come from their unique set up or are related to something in scope for connect rpc.
