### ISSUE TITLE
Deno example

### ISSUE THREAD

**Issue by Manzanit0** [connectrpc/examples-es#1885]
👋🏼 Hi!

I've been trying to get something working with Deno, but I haven't been able so far. I was wondering if it's possible at all, since I'm not really familiar with the ecosystem. I was hoping you could point me in the right direction?

I put together the following example with the issue I'm getting in case it helps: https://github.com/Manzanit0/deno-connectrpc-repro

Thanks!

**Comment by Manzanit0** [comment]
I managed to fix the issue by downgrading the toolchain to v1.x. I'm unsure why v2.x wasn't working though.

See: https://github.com/Manzanit0/deno-connectrpc-repro/commit/8ada0c4013a3fa433eaa5bea9eb5be832ad2c623

**Comment by timostamm** [comment]
The repro has the file `gen/es/greet_connect.ts`, generated by `@connectrpc/protoc-gen-connect-es`. V2 doesn't have this plugin anymore, so I think you've been mixing v1 code with v2 code, which would explain the missing export.
