### ISSUE TITLE
Upgrade to React-Native v0.76.0

### ISSUE THREAD

**Issue by smaye81** [connectrpc/examples-es#2134]
React-Native v0.76 has been [released](https://reactnative.dev/blog/2024/10/23/release-0.76-new-architecture), but Expo [does not support](https://reactnative.dev/blog/2024/10/23/release-0.76-new-architecture#upgrade-to-076) it until SDK 52, which is not yet released. Once it is, we should upgrade the example.

**Comment by hollanderbart** [comment]
Expo 52 is released. Can the example please be upgraded?

**Comment by timostamm** [comment]
https://github.com/connectrpc/connect-es/issues/1363 reports an issue where streaming calls continue when they are aborted after reading the first message. When we update the example, we should give it a try to confirm, and add a note to the example, linking to an upstream bug report.
