### ISSUE TITLE
can i use in miniprogram？there is no provide api like Headers

### ISSUE THREAD

**Issue by xixihhhh** [connectrpc/examples-es#2137]

**Comment by timostamm** [comment]
`@connectrpc/connect` requires the `Headers` type from the fetch API, and the transports from `@connectrpc/connect-web` for the gRPC-Web and the Connect protocol also requires `fetch` itself.

I'm not familiar with miniprogram. If it doesn't provide these APIs, it is not possible to use Connect-ES on this platform easily.
It's possible to bring your own `Headers` implementation and write your own transport, but it will be quite a bit of work.

**Comment by xixihhhh** [comment]
> `@connectrpc/connect` requires the `Headers` type from the fetch API, and the transports from `@connectrpc/connect-web` for the gRPC-Web and the Connect protocol also requires `fetch` itself.
> 
> I'm not familiar with miniprogram. If it doesn't provide these APIs, it is not possible to use Connect-ES on this platform easily. It's possible to bring your own `Headers` implementation and write your own transport, but it will be quite a bit of work.

Thank you for your answer. Mini-programs are extremely popular in China. They are a type of program similar to web pages within WeChat. They have restrictions on APIs such as Headers and TextEncoder. I used polyfill and got them to run normally.
